#ifndef RANDO_TYPES_H
#define RANDO_TYPES_H

typedef enum {
    RCTYPE_UNKNOWN,
    RCTYPE_MAJOR,
    RCTYPE_MAX,
} RandoCheckType;

typedef enum {
    RC_UNKNOWN,
    RC_BBH_RED_COIN_01,
    RC_BBH_RED_COIN_02,
    RC_BBH_RED_COIN_03,
    RC_BBH_RED_COIN_04,
    RC_BBH_RED_COIN_05,
    RC_BBH_RED_COIN_06,
    RC_BBH_RED_COIN_07,
    RC_BBH_RED_COIN_08,
    RC_BOB_STAR_CHAIN_CHOMP,
    RC_BOB_STAR_KING_BOB,
    RC_BOB_STAR_RED_COIN,
    RC_BOB_RED_COIN_01,
    RC_BOB_RED_COIN_02,
    RC_BOB_RED_COIN_03,
    RC_BOB_RED_COIN_04,
    RC_BOB_RED_COIN_05,
    RC_BOB_RED_COIN_06,
    RC_BOB_RED_COIN_07,
    RC_BOB_RED_COIN_08,
    RC_CCM_RED_COIN_01,
    RC_CCM_RED_COIN_02,
    RC_CCM_RED_COIN_03,
    RC_CCM_RED_COIN_04,
    RC_CCM_RED_COIN_05,
    RC_CCM_RED_COIN_06,
    RC_CCM_RED_COIN_07,
    RC_CCM_RED_COIN_08,
    RC_CMC_RED_COIN_01,
    RC_CMC_RED_COIN_02,
    RC_CMC_RED_COIN_03,
    RC_CMC_RED_COIN_04,
    RC_CMC_RED_COIN_05,
    RC_CMC_RED_COIN_06,
    RC_CMC_RED_COIN_07,
    RC_CMC_RED_COIN_08,
    RC_SNL_RED_COIN_01,
    RC_SNL_RED_COIN_02,
    RC_SNL_RED_COIN_03,
    RC_SNL_RED_COIN_04,
    RC_SNL_RED_COIN_05,
    RC_SNL_RED_COIN_06,
    RC_SNL_RED_COIN_07,
    RC_SNL_RED_COIN_08,
    RC_SSL_RED_COIN_01,
    RC_SSL_RED_COIN_02,
    RC_SSL_RED_COIN_03,
    RC_SSL_RED_COIN_04,
    RC_SSL_RED_COIN_05,
    RC_SSL_RED_COIN_06,
    RC_SSL_RED_COIN_07,
    RC_SSL_RED_COIN_08,
    RC_WHF_RED_COIN_01,
    RC_WHF_RED_COIN_02,
    RC_WHF_RED_COIN_03,
    RC_WHF_RED_COIN_04,
    RC_WHF_RED_COIN_05,
    RC_WHF_RED_COIN_06,
    RC_WHF_RED_COIN_07,
    RC_WHF_RED_COIN_08,
    RC_MAX,
} RandoCheckId;

typedef enum {
    RITYPE_UNKNOWN,
    RITYPE_COIN,
    RITYPE_STAR,
    RITYPE_MAX,
} RandoItemType;

typedef enum {
    RI_UNKNOWN,
    RI_COIN_RED,
    RI_STAR,
    RI_MAX,
} RandoItemId;

typedef enum {
    RR_MAX,
} RandoRegionId;

typedef enum {
    RO_MAX,
} RandoOptionId;

typedef enum {
    RO_GENERIC_OFF,
    RO_GENERIC_ON,
} RandoOptionGenericOffOn;

typedef enum {
    RO_LOGIC_GLITCHLESS,
    RO_LOGIC_NO_LOGIC,
} RandoOptionLogic;

typedef enum {
    RANDO_INF_MAX,
} RandoInf;

typedef enum {
    RE_MAX,
} RandoEvent;

#endif // RANDO_TYPES_H
