name: MacOS Validation
on: [pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies
        run: brew install sdl2 libpng glew ninja cmake libzip nlohmann-json tinyxml2 spdlog vorbis-tools
      - name: Build
        run: |
          cmake -H. -Bbuild-cmake -GNinja -DCMAKE_BUILD_TYPE=Release
          cmake --build build-cmake -j
      - name: Create Package
        run: |
          mkdir ghostship-release
          mv build-cmake/Ghostship ghostship-release/
      - name: Publish packaged artifacts
        uses: actions/upload-artifact@v4
        with:
            name: ghostship-mac-x64
            path: ghostship-release
            retention-days: 1